services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: adil-value-objects-app
    restart: always
    working_dir: /var/www/html
    ports:
      - 8006:80
    volumes:
      - ../:/var/www/html